### ISSUE TITLE
Post/thread icons disappeared

### ISSUE THREAD

**Issue by Deleetdk** [openpsych/forum#1]
For some reason these got lost after the update. They were annoying to begin with, but now they are bugged.

![mybb icons](https://cloud.githubusercontent.com/assets/6759913/19925937/65851746-a0f2-11e6-882f-5b9e2113840b.jpg)

Not sure what's causing the issue, aside from 403.

https://www.openpsych.net/forum/images/icons/tongue.gif

Direct link to one of them. Maybe look at server folder to see if files are missing from the folder. Maybe permissions issue?

**Comment by onbjerg** [comment]
They're most likely in the backup directory under images. Just copy them.

**Comment by Deleetdk** [comment]
I'd rather just disable them entirely if possible.

**Comment by onbjerg** [comment]
@Deleetdk If you give the Developer group administrative privileges again, then I'll disable them for you 😊

**Comment by Deleetdk** [comment]
I put you in the admin group instead.

**Comment by Deleetdk** [comment]
No update on this. Users still complain. pls fix

**Comment by onbjerg** [comment]
@Deleetdk Fixed.
