### ISSUE TITLE
Mass email does not work

### ISSUE THREAD

**Issue by Deleetdk** [openpsych/forum#3]
There are no logs. No errors when one runs the test. In fact the test produces an empty reply from the server. PHP version problem? Missing email sender causing invisible bug?

https://docs.mybb.com/1.8/faq/mail/
https://openpsych.net/forum/mail_test.php

It is odd because the regular emails to users work, so it must be some special functionality related to mass emails.

**Comment by onbjerg** [comment]
@Deleetdk Does it work now?

**Comment by Deleetdk** [comment]
Sorry, forgot to update this issue. Together with Laird, we figured out the problem back in December. The issue was not that it doesn't work at all, but that the email details are improper. Hence, the emails tend to end up in he spam folder and it appears they aren't being sent. All mine did in fact end up in the gmail spam folder.

I think better details would be:

Sender: OpenPsych Forums <noreply@openpsych.net>
Receiver: [user's email]

**Comment by Deleetdk** [comment]
We're not sending out a lot of email. I only use mass emails for notifying reviewers of submissions. This happens maybe 1-3 times a month and sends to something like 5-10 people.

**Comment by onbjerg** [comment]
Resolved. Set SPF and DKIM in DNS.
